# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='\u8ba1\u7b97\u673a', max_length=20, verbose_name='\u6240\u5c5e\u7c7b\u522b'),
        ),
    ]
