# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_pre_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u8f6e\u64ad'),
        ),
    ]
